"""Compile tool manifests into governor configuration.

The mapping semantics are the SAME as axor-lab's canonical compilation
(``lab_contracts.canonical.compiled_governor_config`` /
``lab_runner.axor_backend.governor_config``):

- **egress_sinks** — tools whose effect can resolve to EXPORT or EXEC
  (default_class or any ``resolve`` rule class);
- **untrusted_sources** — tools declaring ``untrusted_fields``, with the
  per-tool field patterns kept alongside;
- **driving_args** — each tool's ``effect.driving_args``;
- **value_policies** — a policy allowlist becomes an enum destination policy on
  each egress sink's first driving arg (default ``recipient``) — the sound,
  paraphrase-proof control the kernel supersedes taint with.

Two outputs of the same compilation:

- ``governor_kwargs`` → kwargs for ``axor_core.governor.ToolCallGovernor``;
- ``governance_yaml`` → a declarative ``axor_core.config.GovernanceConfig``
  YAML (generated by hand, no pyyaml — JSON string quoting is valid YAML).
"""

from __future__ import annotations

import json

EGRESS_CLASSES = frozenset({"EXPORT", "EXEC"})  # same as lab_contracts.semantics
_DEFAULT_ALLOWLIST_ARG = "recipient"


def compile_manifests(
    manifests: list[dict[str, object]],
    policy: dict[str, object] | None = None,
) -> dict[str, object]:
    """The canonical compilation (mirrors lab's ``compiled_governor_config``)."""
    egress: list[str] = []
    untrusted_sources: list[str] = []
    sensitive_sources: list[str] = []
    driving: dict[str, list[str]] = {}
    taint_fields: dict[str, list[str]] = {}
    for manifest in manifests:
        tool_id = str(manifest.get("id"))
        effect: dict[str, object] = manifest.get("effect", {}) or {}  # type: ignore[assignment]
        classes = {str(effect.get("default_class"))}
        classes.update(str(rule["class"]) for rule in effect.get("resolve", []))  # type: ignore[union-attr]
        if classes & EGRESS_CLASSES:
            egress.append(tool_id)
        fields = [str(p) for p in manifest.get("untrusted_fields", [])]  # type: ignore[union-attr]
        if fields:
            untrusted_sources.append(tool_id)
            taint_fields[tool_id] = sorted(fields)
        if manifest.get("sensitive_fields"):
            sensitive_sources.append(tool_id)
        args = [str(a) for a in effect.get("driving_args", [])]  # type: ignore[union-attr]
        if args:
            driving[tool_id] = args
    egress.sort()
    untrusted_sources.sort()
    sensitive_sources.sort()
    value_policies: dict[str, object] = {}
    allowlist = (policy or {}).get("allowlist")
    if allowlist:
        resolved = [str(v) for v in allowlist]  # type: ignore[union-attr]
        for sink in egress:
            arg = (driving.get(sink) or [_DEFAULT_ALLOWLIST_ARG])[0]
            value_policies[sink] = {arg: {"enum": resolved}}
    return {
        "egress_sinks": egress,
        "untrusted_sources": untrusted_sources,
        "sensitive_sources": sensitive_sources,
        "untrusted_fields": taint_fields,
        "driving_args": driving,
        "value_policies": value_policies,
    }


def governor_kwargs(
    manifests: list[dict[str, object]],
    policy: dict[str, object] | None = None,
) -> dict[str, object]:
    """Kwargs to splat into ``axor_core.governor.ToolCallGovernor(**kwargs)``.

    Same shape as axor-lab's ``lab_runner.axor_backend.governor_config``; the
    per-field ``untrusted_fields`` map is not a governor kwarg and stays in
    ``compile_manifests`` output only.
    """
    canon = compile_manifests(manifests, policy)
    kwargs: dict[str, object] = {
        "egress_sinks": set(canon["egress_sinks"]),  # type: ignore[arg-type]
        "untrusted_sources": set(canon["untrusted_sources"]),  # type: ignore[arg-type]
        "driving_args": dict(canon["driving_args"]),  # type: ignore[arg-type]
    }
    if canon["sensitive_sources"]:
        kwargs["sensitive_sources"] = set(canon["sensitive_sources"])  # type: ignore[arg-type]
    if canon["value_policies"]:
        kwargs["value_policies"] = canon["value_policies"]
    return kwargs


def governance_yaml(
    manifests: list[dict[str, object]],
    policy: dict[str, object] | None = None,
) -> str:
    """A ``GovernanceConfig.from_yaml``-loadable YAML for the compiled manifests.

    Value policies use GovernanceConfig's predicate form
    (``{arg, kind: enum, allowed: [...]}``), not the raw governor-kwarg form.
    """
    canon = compile_manifests(manifests, policy)
    lines: list[str] = [
        "# governance.yaml — generated by axor-wrap from "
        f"{len(manifests)} tool manifest(s)",
        "# load with axor_core.config.GovernanceConfig.from_yaml(...) "
        "(needs axor-core[config])",
    ]
    _yaml_list(lines, "untrusted_sources", canon["untrusted_sources"])  # type: ignore[arg-type]
    _yaml_list(lines, "sensitive_sources", canon["sensitive_sources"])  # type: ignore[arg-type]
    _yaml_list(lines, "egress_sinks", canon["egress_sinks"])  # type: ignore[arg-type]
    driving: dict[str, list[str]] = canon["driving_args"]  # type: ignore[assignment]
    if driving:
        lines.append("driving_args:")
        for tool in sorted(driving):
            lines.append(f"  {_q(tool)}:")
            lines.extend(f"    - {_q(arg)}" for arg in driving[tool])
    value_policies: dict[str, dict[str, dict[str, list[str]]]] = canon["value_policies"]  # type: ignore[assignment]
    if value_policies:
        lines.append("value_policies:")
        for tool in sorted(value_policies):
            lines.append(f"  {_q(tool)}:")
            for arg, spec in value_policies[tool].items():
                lines.append(f"    - arg: {_q(arg)}")
                lines.append("      kind: enum")
                lines.append("      allowed:")
                lines.extend(f"        - {_q(v)}" for v in spec["enum"])
    return "\n".join(lines) + "\n"


def _yaml_list(lines: list[str], key: str, values: list[str]) -> None:
    if not values:
        return
    lines.append(f"{key}:")
    lines.extend(f"  - {_q(v)}" for v in values)


def _q(value: str) -> str:
    # JSON string quoting is valid YAML; always quoting sidesteps YAML's implicit
    # typing (a tool named "on" or "1.0" must stay a string)
    return json.dumps(str(value))
